name: deploy-cart-service

on:
  push:
    branches: ["master"]

jobs:
  build:
      runs-on: ubuntu-latest
      

      strategy:
        matrix:
          node-version: [18.x] 

      steps: 
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node-version }}

          - name: Test Cart service
            working-directory: ./cart-service
            run: |
              npm ci
              npm test

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: build docker image
          - uses: docker/build-push-action@v6
            with:
              push: true
              tags: ${{secrets.DOCKERHUB_USERNAME}}/rabbitmq
